package Vista.Admin;

import Controlador.Admin_O;
import Controlador.Admin_PI;
import Vista.Tour.IAdminTour;

/**
 *
 * @author LENOVO
 */
public class IAdm_Comite extends javax.swing.JFrame {

    /**
     * Creates new form I_AdmSys
     */
    public IAdm_Comite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonObras = new javax.swing.JButton();
        jButtonPI = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonTour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COPRED - Administración Comité");
        setPreferredSize(new java.awt.Dimension(500, 156));
        setResizable(false);

        jButtonObras.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonObras.setText("Administrar Obras");
        jButtonObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrasActionPerformed(evt);
            }
        });

        jButtonPI.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonPI.setText("Administrar Puntos de Interés");
        jButtonPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPIActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonVolver.setText("Salir");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel1.setText("Seleccione una opción:");

        jButtonTour.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonTour.setText("Administrar Tour");
        jButtonTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVolver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonObras)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonTour, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPI))))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonObras)
                    .addComponent(jButtonPI)
                    .addComponent(jButtonTour))
                .addGap(31, 31, 31)
                .addComponent(jButtonVolver)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Administrar Sistema");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        IAcceso iAcceso = new IAcceso();
        
        iAcceso.setVisible(true);
        iAcceso.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrasActionPerformed
        Admin_O ctrlObras = Admin_O.getInstance();
        
        ctrlObras.instanceAdmObras();
        this.dispose();
    }//GEN-LAST:event_jButtonObrasActionPerformed

    private void jButtonPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPIActionPerformed
       Admin_PI ctrlPI = Admin_PI.getInstance();
       
       ctrlPI.instanceAdmPI();
       this.dispose();
    }//GEN-LAST:event_jButtonPIActionPerformed

    private void jButtonTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTourActionPerformed
        IAdminTour tour = new IAdminTour();
        
        tour.setVisible(true);
        tour.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonTourActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObras;
    private javax.swing.JButton jButtonPI;
    private javax.swing.JButton jButtonTour;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
