/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.PI;

import Controlador.Admin_PI;
import Data.Data;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class ICrearPI extends javax.swing.JFrame {

    /**
     * Creates new form I_RegObra
     */
    public ICrearPI() {
        initComponents();
        
        //Para Pruebas | Obras cableadas
        //Data.patrimonio.setObra();
        
        for(int i=0;i<12;i++){
            jComboBoxUbicacion.addItem(Data.ubicacion[i]);
            jComboBoxUbiObras.addItem(Data.ubicacion[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldCoordenada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxUbicacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBusqueda = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRelacionadas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxUbiObras = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COPRED - Crear Punto de Interés");
        setResizable(false);

        jTextFieldCoordenada.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextFieldCoordenada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCoordenadaActionPerformed(evt);
            }
        });
        jTextFieldCoordenada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCoordenadaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setText("Coordenada:");

        jComboBoxUbicacion.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jComboBoxUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUbicacionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("Ubicación:");

        jLabelError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));

        jButtonConfirmar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableBusqueda.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTableBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBusqueda.setShowHorizontalLines(false);
        jTableBusqueda.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableBusqueda);

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTableRelacionadas.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTableRelacionadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRelacionadas.setShowHorizontalLines(false);
        jTableRelacionadas.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTableRelacionadas);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel6.setText("Seleccione las obras a relacionar con el punto de interés:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel7.setText("Obras relacionadas:");

        jComboBoxUbiObras.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jComboBoxUbiObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUbiObrasActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel9.setText("Ubicación de obras:");

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCoordenada))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jComboBoxUbiObras, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4)
                                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(50, 50, 50)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCoordenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUbiObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonConfirmar))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        Admin_PI ctrlPI = Admin_PI.getInstance();
        int coordenada;
        
        ArrayList<String> secuencia_ID = new ArrayList();
        
        for(int fila = 0; fila < jTableRelacionadas.getRowCount(); fila++) {
            secuencia_ID.add(jTableRelacionadas.getValueAt(fila, 0).toString());    
        }
        
        if(jTextFieldCoordenada.getText().isEmpty()) {
            coordenada = 1000;
        } else {
            coordenada = Integer.parseInt(jTextFieldCoordenada.getText());
        }
        
        String mensaje = ctrlPI.crearPI(jComboBoxUbicacion.getSelectedItem().toString(), coordenada, secuencia_ID);    
        
        if(mensaje.equals("")){
            ctrlPI.instanceAdmPI();
            this.dispose();
        }else{
            jLabelError.setText("Error: "+ mensaje);
        }
        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        Admin_PI ctrlPI = Admin_PI.getInstance();
        
        ctrlPI.instanceAdmPI();
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableRelacionadas.getModel();
        DefaultTableModel modelo1 = (DefaultTableModel) jTableBusqueda.getModel();
        
        boolean flag = true;
        
        String[] fila = new String[3];
        int seleccion = jTableBusqueda.getSelectedRow();
        
        if(seleccion != -1) {
            int i=0;
            do {
                if(i < jTableRelacionadas.getRowCount() && jTableBusqueda.getValueAt(seleccion, 0).toString().equals(jTableRelacionadas.getValueAt(i, 0).toString())) {
                    flag = false;
                    jLabelError.setText("La Obra ya está asociada");
                }
                i++;
            } while(i < jTableRelacionadas.getRowCount() && !jTableBusqueda.getValueAt(seleccion, 0).toString().equals(jTableRelacionadas.getValueAt(i, 0).toString()));
            
            if(flag) {
                fila[0] = jTableBusqueda.getValueAt(seleccion, 0).toString();
                fila[1] = jTableBusqueda.getValueAt(seleccion, 1).toString();
                fila[2] = jTableBusqueda.getValueAt(seleccion, 2).toString();

                modelo.addRow(fila);
                //modelo1.removeRow(seleccion);       
            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableBusqueda.getModel();
        DefaultTableModel modelo1 = (DefaultTableModel) jTableRelacionadas.getModel();
        
        String[] fila = new String[3];
        int seleccion = jTableRelacionadas.getSelectedRow();
        
        boolean flag = true;
        
        if(seleccion != -1) {
            int i=0;
            do {
                if(i < jTableBusqueda.getRowCount() && jTableRelacionadas.getValueAt(seleccion, 0).toString().equals(jTableBusqueda.getValueAt(i, 0).toString())) {
                    flag = false;
                }
                i++;
            } while(i < jTableBusqueda.getRowCount() && !jTableRelacionadas.getValueAt(seleccion, 0).toString().equals(jTableBusqueda.getValueAt(i, 0).toString()));
            
            if(flag) {
                fila[0] = jTableRelacionadas.getValueAt(seleccion, 0).toString();
                fila[1] = jTableRelacionadas.getValueAt(seleccion, 1).toString();
                fila[2] = jTableRelacionadas.getValueAt(seleccion, 2).toString();

                modelo.addRow(fila);
            }
            
            modelo1.removeRow(seleccion);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableBusqueda.getModel();
        Admin_PI ctrlPI = Admin_PI.getInstance();
        
        while(modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        
        String[] fila = new String[3];
        ArrayList<HashMap> lista = ctrlPI.buscarObrasUbi(jComboBoxUbiObras.getSelectedItem().toString());
        
        if(lista.isEmpty()){
            jLabelError.setText("No hay obras en la ubicación seleccionada");
        } else {     
            for(HashMap<String,String> obra: lista){
                fila[0] = obra.get("Identificador");
                fila[1] = obra.get("Titulo");
                fila[2] = obra.get("Autor");
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBoxUbiObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUbiObrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUbiObrasActionPerformed

    private void jTextFieldCoordenadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCoordenadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCoordenadaActionPerformed

    private void jComboBoxUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUbicacionActionPerformed

    private void jTextFieldCoordenadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCoordenadaKeyTyped
        if(jTextFieldCoordenada.getText().length()>4){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCoordenadaKeyTyped



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxUbiObras;
    private javax.swing.JComboBox<String> jComboBoxUbicacion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableBusqueda;
    private javax.swing.JTable jTableRelacionadas;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCoordenada;
    // End of variables declaration//GEN-END:variables
}
