/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.PI;

import Controlador.Admin_PI;
import Data.Data;
import Vista.Admin.IAdm_Comite;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class IModPI extends javax.swing.JFrame {
    char disponibilidad;
    int coordenadaAnterior;
    int coordenada;
            
    /**
     * Creates new form I_RegObra
     */
    public IModPI() {
        initComponents();
    }
    
    public IModPI(int coordenada) {
        initComponents();
              
        Admin_PI ctrlPI = Admin_PI.getInstance();

        this.disponibilidad = ctrlPI.getPI(coordenada).get_Disponibilidad();
        this.coordenadaAnterior = coordenada;
        
        DefaultTableModel modelo = (DefaultTableModel) jTableRelacionadas.getModel();
        
        for(int i=0;i<12;i++){
            jComboBoxUbicacion.addItem(Data.ubicacion[i]);
            jComboBoxUbiObras.addItem(Data.ubicacion[i]);
        }
        
        jComboBoxUbicacion.setSelectedItem(ctrlPI.getPI(coordenada).get_Ubicacion());
        jTextFieldCoordenada.setText(coordenada + "");

        while(modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        
        String[] fila = new String[3];
        ArrayList<HashMap> lista = ctrlPI.getObrasAsociadasPI(coordenada);
        
        for(HashMap<String,String> obra: lista){
            fila[0] = obra.get("Identificador");
            fila[1] = obra.get("Titulo");
            fila[2] = obra.get("Autor");;
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel6 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jComboBoxUbiObras = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextFieldCoordenada = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxUbicacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRelacionadas = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableBusqueda = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COPRED - Modificar Punto de Interés");
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel6.setText("Seleccione las obras a relacionar con el punto de interés:");

        jLabelError.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel7.setText("Obras relacionadas:");

        jButtonConfirmar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jComboBoxUbiObras.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jButtonCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel9.setText("Ubicación de obras:");

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextFieldCoordenada.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextFieldCoordenada.setText("1");

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setText("Coordenada:");

        jComboBoxUbicacion.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("Ubicación:");

        jTableRelacionadas.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTableRelacionadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRelacionadas.setShowHorizontalLines(false);
        jTableRelacionadas.setShowVerticalLines(false);
        jScrollPane4.setViewportView(jTableRelacionadas);

        jTableBusqueda.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTableBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBusqueda.setShowHorizontalLines(false);
        jTableBusqueda.setShowVerticalLines(false);
        jScrollPane5.setViewportView(jTableBusqueda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxUbiObras, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCoordenada, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 362, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCoordenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUbiObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCancelar)
                        .addComponent(jButtonConfirmar)))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed

        Admin_PI ctrlPI = Admin_PI.getInstance(); 
        String ubicacion = jComboBoxUbicacion.getSelectedItem().toString();
        int coordenada = Integer.parseInt(jTextFieldCoordenada.getText());
        ArrayList<String> secuencia_ID = new ArrayList();
        
        for(int fila = 0; fila < jTableRelacionadas.getRowCount(); fila++) {
            secuencia_ID.add(jTableRelacionadas.getValueAt(fila, 0).toString());    
        }
        
        String mensaje = ctrlPI.validarCoordenada(coordenada,coordenadaAnterior);
        
        if(mensaje.equals("")){
            IModDisp iDispoPI = new IModDisp(ubicacion, disponibilidad, coordenada, secuencia_ID, coordenadaAnterior);    
        
            iDispoPI.setVisible(true);
            iDispoPI.setLocationRelativeTo(null);
            this.dispose();
        } else {
            jLabelError.setText(mensaje);
        }    
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        Admin_PI ctrlPI = Admin_PI.getInstance();
        IAdm_Comite iAdmSys = new IAdm_Comite();
        
        iAdmSys.setVisible(true);
        iAdmSys.setLocationRelativeTo(null);
        ctrlPI.instanceAdmPI();
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableBusqueda.getModel();
        Admin_PI ctrlPI = Admin_PI.getInstance();
        
        while(modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        
        String[] fila = new String[3];
        ArrayList<HashMap> lista = ctrlPI.buscarObrasUbi(jComboBoxUbiObras.getSelectedItem().toString());
        
        
        if(lista.isEmpty()){
            jLabelError.setText("No hay obras en la ubicación seleccionada");
        } else {   
            for(HashMap<String,String> obra: lista){
                fila[0] = obra.get("Identificador");
                fila[1] = obra.get("Titulo");
                fila[2] = obra.get("Autor");
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableRelacionadas.getModel();
        DefaultTableModel modelo1 = (DefaultTableModel) jTableBusqueda.getModel();
        
        boolean flag = true;
        
        String[] fila = new String[3];
        int seleccion = jTableBusqueda.getSelectedRow();
        
        if(seleccion != -1) {
            int i=0;
            do {
                if(i < jTableRelacionadas.getRowCount() && jTableBusqueda.getValueAt(seleccion, 0).toString().equals(jTableRelacionadas.getValueAt(i, 0).toString())) {
                    flag = false;
                    jLabelError.setText("La Obra ya está asociada");
                }
                i++;
            } while(i < jTableRelacionadas.getRowCount() && !jTableBusqueda.getValueAt(seleccion, 0).toString().equals(jTableRelacionadas.getValueAt(i, 0).toString()));
            
            if(flag) {
                fila[0] = jTableBusqueda.getValueAt(seleccion, 0).toString();
                fila[1] = jTableBusqueda.getValueAt(seleccion, 1).toString();
                fila[2] = jTableBusqueda.getValueAt(seleccion, 2).toString();

                modelo.addRow(fila);
                //modelo1.removeRow(seleccion);       
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableBusqueda.getModel();
        DefaultTableModel modelo1 = (DefaultTableModel) jTableRelacionadas.getModel();
        
        String[] fila = new String[3];
        int seleccion = jTableRelacionadas.getSelectedRow();
        
        boolean flag = true;
        
        if(seleccion != -1) {
            int i=0;
            do {
                if(i < jTableBusqueda.getRowCount() && jTableRelacionadas.getValueAt(seleccion, 0).toString().equals(jTableBusqueda.getValueAt(i, 0).toString())) {
                    flag = false;
                }
                i++;
            } while(i < jTableBusqueda.getRowCount() && !jTableRelacionadas.getValueAt(seleccion, 0).toString().equals(jTableBusqueda.getValueAt(i, 0).toString()));
            
            if(flag) {
                fila[0] = jTableRelacionadas.getValueAt(seleccion, 0).toString();
                fila[1] = jTableRelacionadas.getValueAt(seleccion, 1).toString();
                fila[2] = jTableRelacionadas.getValueAt(seleccion, 2).toString();

                modelo.addRow(fila);
            }
            
            modelo1.removeRow(seleccion);
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxUbiObras;
    private javax.swing.JComboBox<String> jComboBoxUbicacion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableBusqueda;
    private javax.swing.JTable jTableRelacionadas;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCoordenada;
    // End of variables declaration//GEN-END:variables
}
