/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Obra;

import Controlador.Admin_O;
import Data.Data;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LENOVO
 */
public class IModO extends javax.swing.JFrame {

File fichero;
    
    String identificadorAnterior;

    public IModO(String identificador) {
        initComponents();
        
        this.identificadorAnterior = identificador;
        Admin_O ctrlObras = Admin_O.getInstance();
        HashMap<String, String> obra = ctrlObras.consultar(identificador);
        Icon img = ctrlObras.get_Imagen(identificador);
        
        //String CB= obra.get("Ubicacion");

        for(int i=0;i<12;i++){
            jComboBoxUbi.addItem(Data.ubicacion[i]);
        }
        for(int i=0;i<3;i++){
            jComboBoxEstatus.addItem("" + Data.estatus[i]);
        }
        jTextFieldTitulo.setText(obra.get("Titulo"));
        jTextFieldID.setText(obra.get("Identificador"));
        jTextFieldAñoC.setText(obra.get("ACreacion"));
        jTextFieldApellidoA.setText(obra.get("ApellidoA"));
        jTextFieldNombreA.setText(obra.get("NombreA"));
        jComboBoxUbi.setSelectedItem(obra.get("Ubicacion"));
        jComboBoxEstatus.setSelectedItem(obra.get("Estatus"));
        jTextAreaDescripcion.setText(obra.get("Descripcion"));
        if (img== null){
            jLabelImg.setText("Sin Imagen");
        }else jLabelImg.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellidoA = new javax.swing.JTextField();
        jComboBoxUbi = new javax.swing.JComboBox<>();
        jTextFieldAñoC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btncargarFoto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEstatus = new javax.swing.JComboBox<>();
        jLabelImg = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreA = new javax.swing.JTextField();
        jButtonconfirmar = new javax.swing.JButton();
        jButtoncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COPRED - Modificar Obra");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setText("Año de creación:");

        jTextFieldID.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyTyped(evt);
            }
        });

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);
        jTextAreaDescripcion.setWrapStyleWord(true);
        jTextAreaDescripcion.setLineWrap(true);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("Identificador:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel7.setText("Descripción:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("Nombre autor:");

        jTextFieldApellidoA.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextFieldApellidoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoAActionPerformed(evt);
            }
        });
        jTextFieldApellidoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoAKeyTyped(evt);
            }
        });

        jComboBoxUbi.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jComboBoxUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUbiActionPerformed(evt);
            }
        });

        jTextFieldAñoC.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextFieldAñoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAñoCKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel6.setText("Estatus:");

        jTextFieldTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel1.setText("Título:");

        btncargarFoto.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btncargarFoto.setText("Cargar imagen");
        btncargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarFotoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel9.setText("Ubicación:");

        jComboBoxEstatus.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jComboBoxEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstatusActionPerformed(evt);
            }
        });

        jLabelImg.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabelImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelError.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel4.setText("Apellido autor:");

        jTextFieldNombreA.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextFieldNombreA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreAActionPerformed(evt);
            }
        });
        jTextFieldNombreA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreAKeyTyped(evt);
            }
        });

        jButtonconfirmar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonconfirmar.setText("Confirmar");
        jButtonconfirmar.setFocusable(false);
        jButtonconfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonconfirmar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconfirmarActionPerformed(evt);
            }
        });

        jButtoncancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtoncancelar.setText("Cancelar");
        jButtoncancelar.setFocusable(false);
        jButtoncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtoncancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncargarFoto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldAñoC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)))
                                        .addComponent(jLabel9)
                                        .addComponent(jComboBoxUbi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxEstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombreA)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextFieldID)))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonconfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtoncancelar))
                            .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAñoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncargarFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtoncancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonconfirmar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApellidoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoAActionPerformed

    private void jComboBoxEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstatusActionPerformed

    private void jButtonconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconfirmarActionPerformed
        Admin_O ctrlObras = Admin_O.getInstance();
        String mensaje = ctrlObras.modificar(jTextFieldTitulo.getText(),jTextFieldID.getText(), jTextFieldAñoC.getText(), jTextFieldNombreA.getText(), jComboBoxUbi.getSelectedItem().toString(), jComboBoxEstatus.getSelectedItem().toString().charAt(0), jTextAreaDescripcion.getText(), jLabelImg.getIcon(), jTextFieldApellidoA.getText(),identificadorAnterior);
        if(mensaje.equals("")){
            ctrlObras.instanceAdmObras();
            this.dispose();
        }else{
            jLabelError.setText("Error: "+ mensaje);
        }
    }//GEN-LAST:event_jButtonconfirmarActionPerformed

    private void jButtoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelarActionPerformed
        Admin_O ctrlObras = Admin_O.getInstance();
        ctrlObras.instanceAdmObras();
        this.dispose();
    }//GEN-LAST:event_jButtoncancelarActionPerformed

    private void jComboBoxUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUbiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUbiActionPerformed

    private void jTextFieldNombreAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreAActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void btncargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarFotoActionPerformed
        int resultado;
        cargarFoto ventana = new cargarFoto();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg","png");
        cargarFoto.jfchcargarFoto.setFileFilter(filtro);
        resultado= ventana.jfchcargarFoto.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == resultado){
            fichero = ventana.jfchcargarFoto.getSelectedFile();
            ImageIcon icon = new ImageIcon(fichero.toString());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(jLabelImg.getWidth(), jLabelImg.getHeight(), Image.SCALE_DEFAULT));
            jLabelImg.setText(null);
            jLabelImg.setIcon( icono );
        }
    }//GEN-LAST:event_btncargarFotoActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
         if(jTextFieldTitulo.getText().length()>40){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    private void jTextFieldIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyTyped
        if(jTextFieldID.getText().length()>18){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIDKeyTyped

    private void jTextFieldAñoCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAñoCKeyTyped
       if(jTextFieldAñoC.getText().length()>12){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAñoCKeyTyped

    private void jTextFieldApellidoAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoAKeyTyped
        if(jTextFieldApellidoA.getText().length()>17){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldApellidoAKeyTyped

    private void jTextFieldNombreAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreAKeyTyped
         if(jTextFieldNombreA.getText().length()>12){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreAKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargarFoto;
    private javax.swing.JButton jButtoncancelar;
    private javax.swing.JButton jButtonconfirmar;
    private javax.swing.JComboBox<String> jComboBoxEstatus;
    private javax.swing.JComboBox<String> jComboBoxUbi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldApellidoA;
    private javax.swing.JTextField jTextFieldAñoC;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombreA;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
