/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Obra;

import Controlador.Admin_O;
import java.util.HashMap;  
import javax.swing.Icon;
/**
 *
 * @author LENOVO
 */
public class IUnaO extends javax.swing.JFrame {
    /**
     * Creates new form I_RegObra
     * @param identificador
     */
    public IUnaO(String identificador){
        initComponents();
        
        Admin_O ctrlObras = Admin_O.getInstance();
        HashMap<String, String> obra = ctrlObras.consultar(identificador);
        Icon img = ctrlObras.get_Imagen(identificador);
        
        jTextFieldTitulo.setText(obra.get("Titulo"));
        jTextFieldID.setText(obra.get("Identificador"));
        jTextFieldAñoC.setText(obra.get("ACreacion"));
        jTextFieldApellidoA.setText(obra.get("ApellidoA"));
        jTextFieldNombreA.setText(obra.get("NombreA"));
        jTextFieldUbi.setText(obra.get("Ubicacion"));
        jTextFieldEstatus.setText(obra.get("Estatus"));
        jTextAreaDescripcion.setText(obra.get("Descripcion"));
        if (img== null){
            jLabelImg.setText("Sin Imagen");
        }else{
            jLabelImg.setIcon(img);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUbi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAñoC = new javax.swing.JTextField();
        jTextFieldEstatus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreA = new javax.swing.JTextField();
        jTextFieldApellidoA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COPRED - Consulta de las propiedades de una obra");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jTextFieldUbi.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTextFieldUbi.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldUbi.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel1.setText("Título:");

        jTextFieldAñoC.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTextFieldAñoC.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldAñoC.setEnabled(false);
        jTextFieldAñoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAñoCActionPerformed(evt);
            }
        });

        jTextFieldEstatus.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTextFieldEstatus.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldEstatus.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("Apellido autor:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("Identificador:");

        jTextFieldNombreA.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTextFieldNombreA.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldNombreA.setEnabled(false);

        jTextFieldApellidoA.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTextFieldApellidoA.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldApellidoA.setEnabled(false);
        jTextFieldApellidoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoAActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel4.setText("Nombre autor:");

        jTextFieldTitulo.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTextFieldTitulo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTitulo.setEnabled(false);
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setText("Año de creación:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel7.setText("Descripción:");

        jLabelImg.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabelImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImg.setToolTipText("");

        jTextAreaDescripcion.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaDescripcion.setColumns(1);
        jTextAreaDescripcion.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTextAreaDescripcion.setRows(1);
        jTextAreaDescripcion.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextAreaDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaDescripcion);
        jTextAreaDescripcion.setWrapStyleWord(true);
        jTextAreaDescripcion.setLineWrap(true);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel6.setText("Estatus:");

        jTextFieldID.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldID.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTextFieldID.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldID.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel9.setText("Imagen:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel8.setText("Ubicación");

        jButtonVolver.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonVolver.setText("Aceptar");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAñoC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldApellidoA)))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldUbi, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEstatus)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldNombreA)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldID)))
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAñoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVolver)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        Admin_O ctrlObras = Admin_O.getInstance();
        ctrlObras.instanceAdmObras();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldApellidoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoAActionPerformed

    private void jTextFieldAñoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAñoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAñoCActionPerformed

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldApellidoA;
    private javax.swing.JTextField jTextFieldAñoC;
    private javax.swing.JTextField jTextFieldEstatus;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombreA;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldUbi;
    // End of variables declaration//GEN-END:variables
}
